name: hlint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install lint
        uses: domdere/haskell-lint-action@v1.0.2
        env:
          GITHUB_TOKEN: secrethub://secrethub/github-actions/github/token
        with:
          token: ${{ env.GITHUB_TOKEN }}
